### PR TITLE
Mainly log improvements

### PR DESCRIPTION
**Pull request by tsarbuig**
And I'm not sure about my proposal of adding a timeout on line 1274, but the main problem is that the CMD Terminal closes, and the user does not see the "10 - 50 $LIMIT tokens needed to use this bot....." error message when he does not own LIMIT tokens 

--> how can we keep it displayed without closing terminal ?

### CODE REVIEW

**Comment by tsarbuig** [comment]
+ updated Readme.txt

**Comment by tsarbuig** [comment]
little change to default tokens.json

**Comment by CryptoGnome** [comment]
please re merge this with changes to the exchange selection & timeout removed, those need additional changed to be implemented

**Comment by tsarbuig** [comment]
here you go bro

**Pull request merged**
