### PR TITLE
add websockets and IPC support for pancakeswap.

### PR DESCRIPTION
**Pull request by nathanspace**
According to https://web3py.readthedocs.io/en/stable/providers.html

> IPC (uses local filesystem: fastest and most secure)
> Websockets (works remotely, faster than HTTP)
> HTTP (more nodes support it)

### CODE REVIEW

**Comment by CryptoGnome** [comment]
Looks good can you please push changed to the base settings file as well to include this change

**Comment by CryptoGnome** [comment]
> Looks good can you please push changed to the base settings file as well to include this change

Never mind now that I am at PC I see what you did :D

**Comment by tsarbuig** [comment]
FYI guys I tried to test with wss (wss://bsc-ws-node.nariox.org:443) and it did not work...

Did you try on your side?

**Comment by nathanspace** [comment]
Yes I tried it on my side.

I just tried it again to verify using wss://bsc-ws-node.nariox.org and it worked. I'm not sure what problem you are running into.

**Comment by tsarbuig** [comment]
@nathanspace  can you tell me precisely which value you used in the settings.json ?

Thanks

**Pull request merged**
